<?php

/*
 * Implements hook_token_info();
 */

function drudesk_testtoken_token_info() {
  $node_tokens['category'] = array(
    'name'          =>  t('Test Category'),
    'description'   =>  t('The category of the node.')
  );

  return array(
    'tokens'  =>  array(
      'node'  =>  $node_tokens
    )
  );
}

function drudesk_testtoken_tokens($type, $tokens, array $data = array(), array $options = array()) {
  $replacements = array();

  if ($type == 'node' && !empty($data['node'])) {
    $node = $data['node'];

    foreach ($tokens as $name => $original) {
      if ($name == 'category') {
        $replacements[$original] = !empty($node->field_category['und'][0]['value']) ? $node->field_category['und'][0]['value'] : '';
      }
    }
  }

  return $replacements;
}
